-- ==================================================
-- Exercise: Inserting SQL
-- ==================================================


-- ==================================================
-- Setup Verification
-- ==================================================

-- Confirm that the payment methods were inserted.
SELECT *
FROM PaymentMethod
ORDER BY PaymentMethodId;

-- Answer:
-- 3 rows returned.
-- Payment methods 1, 2, and 3 are available.


-- ==================================================
-- Part 1: Insert Single Records
-- ==================================================

-- 1. Insert Emma Rivera into the Customer table.

INSERT INTO Customer (CustomerName)
VALUES ('Emma Rivera');

-- Answer:
-- INSERT 0 1
-- One customer record was inserted.


-- Insert Noah Gray into the Customer table.

INSERT INTO Customer (CustomerName)
VALUES ('Noah Gray');

-- Answer:
-- INSERT 0 1
-- One customer record was inserted.


-- Verify the two customers.

SELECT *
FROM Customer
WHERE CustomerName IN ('Emma Rivera', 'Noah Gray')
ORDER BY CustomerId;

-- Answer:
-- 2 rows returned.
-- CustomerId 1 was generated for Emma Rivera.
-- CustomerId 2 was generated for Noah Gray.
-- Both customers were successfully inserted.


-- ==================================================
-- Part 1, Question 2: Insert Customer Orders
-- ==================================================

-- 2. Create an order for Emma Rivera using today's date.
-- The subquery retrieves Emma's generated CustomerId.

INSERT INTO CustomerOrder (CustomerId, OrderDate)
VALUES (
    (
        SELECT CustomerId
        FROM Customer
        WHERE CustomerName = 'Emma Rivera'
    ),
    CURRENT_DATE
);

-- Answer:
-- INSERT 0 1
-- One order was inserted for Emma Rivera.


-- Create an order for Noah Gray using today's date.

INSERT INTO CustomerOrder (CustomerId, OrderDate)
VALUES (
    (
        SELECT CustomerId
        FROM Customer
        WHERE CustomerName = 'Noah Gray'
    ),
    CURRENT_DATE
);

-- Answer:
-- INSERT 0 1
-- One order was inserted for Noah Gray.


-- Verify the orders and display the customer names.

SELECT
    co.OrderId,
    c.CustomerName,
    co.OrderDate
FROM CustomerOrder AS co
INNER JOIN Customer AS c
    ON co.CustomerId = c.CustomerId
WHERE c.CustomerName IN ('Emma Rivera', 'Noah Gray')
ORDER BY co.OrderId;

-- Answer:
-- 2 rows returned.
-- OrderId 1 belongs to Emma Rivera.
-- OrderId 2 belongs to Noah Gray.
-- Both orders were successfully inserted with today's date,
-- 2026-08-06.

-- ==================================================
-- Part 2: Insert With an Autogenerated Key
-- ==================================================

-- 3. Insert a payment of $49.99 for Emma's order
-- using PaymentMethodId 1.
-- PaymentId is omitted so PostgreSQL generates it.

INSERT INTO Payment (
    OrderId,
    PaymentMethodId,
    Amount
)
VALUES (
    (
        SELECT co.OrderId
        FROM CustomerOrder AS co
        INNER JOIN Customer AS c
            ON co.CustomerId = c.CustomerId
        WHERE c.CustomerName = 'Emma Rivera'
        ORDER BY co.OrderId
        LIMIT 1
    ),
    1,
    49.99
);

-- Answer:
-- INSERT 0 1
-- One payment was inserted.
-- PostgreSQL automatically generated the PaymentId.


-- Verify Emma's payment.

SELECT
    p.PaymentId,
    c.CustomerName,
    co.OrderId,
    pm.MethodName,
    p.Amount
FROM Payment AS p
INNER JOIN CustomerOrder AS co
    ON p.OrderId = co.OrderId
INNER JOIN Customer AS c
    ON co.CustomerId = c.CustomerId
INNER JOIN PaymentMethod AS pm
    ON p.PaymentMethodId = pm.PaymentMethodId
WHERE c.CustomerName = 'Emma Rivera';

-- Answer:
-- 1 row returned.
-- PaymentId 1 was automatically generated by PostgreSQL.
-- Emma Rivera's OrderId 1 has a $49.99 payment
-- using the Credit Card payment method.


-- ==================================================
-- Part 3: Handle Foreign Keys
-- ==================================================

-- 4. Try inserting a payment using
-- PaymentMethodId 999.
--


INSERT INTO Payment (
    OrderId,
    PaymentMethodId,
    Amount
)
VALUES (
    (
        SELECT co.OrderId
        FROM CustomerOrder AS co
        INNER JOIN Customer AS c
            ON co.CustomerId = c.CustomerId
        WHERE c.CustomerName = 'Noah Gray'
        ORDER BY co.OrderId
        LIMIT 1
    ),
    999,
    20.00
);

-- Answer:
-- The INSERT failed because PaymentMethodId 999
-- does not exist in the PaymentMethod table.

-- PostgreSQL error message:
-- ERROR: insert or update on table "payment" violates foreign key
-- constraint "payment_paymentmethodid_fkey"
-- SQL state: 23503
-- Detail: Key (paymentmethodid)=(999) is not present in table
-- "paymentmethod".

SELECT *
FROM Payment
WHERE PaymentMethodId = 999;

-- Answer:
-- 0 rows returned.
-- PostgreSQL rejected the invalid payment because
-- PaymentMethodId 999 does not exist.


-- ==================================================
-- Part 4: Bulk Insert
-- ==================================================

-- 5. Insert Liam Davis, Olivia Brooks, and
-- Sophia Martinez in one INSERT statement.

INSERT INTO Customer (CustomerName)
VALUES
    ('Liam Davis'),
    ('Olivia Brooks'),
    ('Sophia Martinez');

-- Answer:
-- INSERT 0 3
-- Three customer records were inserted.


-- Verify the bulk customer insert.

SELECT *
FROM Customer
WHERE CustomerName IN (
    'Liam Davis',
    'Olivia Brooks',
    'Sophia Martinez'
)
ORDER BY CustomerId;

-- Answer:
-- 3 rows returned.
-- CustomerId 3 was generated for Liam Davis.
-- CustomerId 4 was generated for Olivia Brooks.
-- CustomerId 5 was generated for Sophia Martinez.
-- All three customers were successfully inserted.


-- ==================================================
-- Part 4, Question 6: Bulk Insert Two Orders
-- ==================================================

-- 6. Insert one order for Liam Davis and one order
-- for Olivia Brooks using today's date.

INSERT INTO CustomerOrder (
    CustomerId,
    OrderDate
)
VALUES
    ( (
            SELECT CustomerId
            FROM Customer
            WHERE CustomerName = 'Liam Davis' ),
        CURRENT_DATE ),
    ( (
        	SELECT CustomerId
            FROM Customer
            WHERE CustomerName = 'Olivia Brooks'
        ),
        CURRENT_DATE );

-- Answer:
-- INSERT 0 2
-- Two customer-order records were inserted.


-- Verify the two bulk-inserted orders.

SELECT
    co.OrderId,
    c.CustomerName,
    co.OrderDate
FROM CustomerOrder AS co
INNER JOIN Customer AS c
    ON co.CustomerId = c.CustomerId
WHERE c.CustomerName IN (
    'Liam Davis',
    'Olivia Brooks'
)
ORDER BY co.OrderId;

-- Answer:
-- 2 rows returned.
-- OrderId 3 was created for Liam Davis.
-- OrderId 4 was created for Olivia Brooks.
-- Both orders were successfully inserted with today's date,
-- 2026-08-06.


-- ==================================================
-- Final Verification
-- ==================================================

-- Display all customers and their orders.

SELECT
    c.CustomerId,
    c.CustomerName,
    co.OrderId,
    co.OrderDate
FROM Customer AS c
LEFT JOIN CustomerOrder AS co
    ON c.CustomerId = co.CustomerId
ORDER BY c.CustomerId, co.OrderId;

-- Answer:
-- 5 rows returned.
-- Emma Rivera, Noah Gray, Liam Davis, and Olivia Brooks
-- each have an order dated 2026-08-06.
-- Sophia Martinez was inserted as a customer but does not
-- have an order, so her OrderId and OrderDate are NULL.


-- Display all successful payments.

SELECT
    p.PaymentId,
    c.CustomerName,
    co.OrderId,
    pm.MethodName,
    p.Amount
FROM Payment AS p
INNER JOIN CustomerOrder AS co
    ON p.OrderId = co.OrderId
INNER JOIN Customer AS c
    ON co.CustomerId = c.CustomerId
INNER JOIN PaymentMethod AS pm
    ON p.PaymentMethodId = pm.PaymentMethodId
ORDER BY p.PaymentId;

-- Answer:
-- 1 row returned.
-- PaymentId 1 belongs to Emma Rivera's OrderId 1.
-- The payment amount is $49.99 and the payment method
-- is Credit Card.